tap "coursier/formulas"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "docker"
brew "docker-compose"
brew "gnupg"
brew "node@16", link: true
brew "openjdk@17"
brew "wget"
brew "yarn"
brew "coursier/formulas/coursier"
